### ISSUE TITLE
MessageLoop: exposing a step method

### ISSUE THREAD

**Issue by Bilal2453** [yue/yue#139]
This is a feature suggestion.

I would love if Yue exposed the wrapped event loop in a way it is possible to integrate it into some other event loop. For example, integrating Yue with the libuv bindings for Lua, Luv.

All we would need to this is either a step method, each time that method is called the event loop would tick once, or, a way of yielding the MessageLoop allowing some other loop to tick (and possibly offering a callback that is called on each MessageLoop tick).

Perhaps, it would make sense to have this on the roadmap of 1.0.0?

**Comment by wahern** [comment]
I'm not very familiar with windowing systems, but I was looking into this exact thing the other day, at least for macOS, and I don't think a step function is possible.

1) macOS's event loop doesn't even seem to let you step. It's either run and block, or exit. You could perhaps repeatedly exit, but I can think of many reasons that might be problematic.

2) With a step function you need an event source to know when to resume, otherwise you're just spinning. However, AFAICT macOS doesn't expose a singular event source (i.e. kqueue descriptor, XNU port) that coalesces all events, even though probably technically feasible--kqueue, like epoll, can query other kqueue descriptors as well as XNU ports, so readiness for trees of  event source can bubble up to a single, pollable source.

Windows is probably even worse in this regard. Gtk might be able to do it, but that doesn't help much if the other three don't.

What you *can* do, at least with macOS and Gtk, is schedule a callback for event sources on file descriptors (including kqueue/epoll descriptors). (Also, in the case of macOS, XNU ports, but you can also put a XNU port behind a kqueue descriptor, so it's just a convenience, not a necessity.)

However, many common event loops have the same problem as windowing event loops--they don't expose a coalesced event source. I'm not sure if libuv has this problem. I stepped away from maintenance awhile ago but the cqueues event loop is designed to be integrated into other event loops--it has a simple stepping function, and exposes a single kqueue/epoll descriptor so you know when to invoke the top-level stepping function. Unfortunately, I never had time to port cqueues to Windows (partly because Windows has a no analog to epoll/kqueue that can coalesce effectively unlimited trees of event sources behind a single pollable object).

I'm currently working on a macOS app using both Yue (GUI) and cqueues (running in a separate POSIX thread and managing async background tasks) on macOS, and it would definitely be useful to be able to register a callback from the main windowing loop whenever a descriptor polls ready, so the GUI can easily respond to events from the cqueues loop. Conceptually this should be fairly trivial as macOS provides a  way to create and install an event source based on a file descriptor (i.e. the top-level cqueues kqueue descriptor). I spent some time digging through the Yue source code to figure out what changes might be needed to make this happen, and will circle back to it at some point if nobody else does. However, I'm very unsure if or how something similar could be done for the Windows flavor of Yue, and thus how any patch might be received. (I don't think it's technically necessary to patch Yue to get this done of macOS, except that if you want to also invoke Yue APIs from the callback it might be necessary to make sure things are properly orchestrated with Yue's signal callback mechanism, which relies on some internal, singleton state.)

**Comment by Bilal2453** [comment]
Thank you William for the great write up! It explained a lot

Hm, that is indeed much more problematic than I initially thought. My knowledge around Cocoa's (or even GTK's) event loops aren't exactly up for the task.
Although, how about at least offering an event that is guaranteed to be fired at a constant(-ish) rate? This way we could step the Luv's event loop manually instead (It should be easy enough to do that, in Luv it should pretty much be just `uv.run("nowait")` for each step until it returns false).

**Comment by Bilal2453** [comment]
I will be closing this, as it does appear to be more complicated than it is worth investing in.  Do note that if you are really bound to a single thread, or you don't/can't patch libuv, there is a third option of using `MessageLoop.postdelayedtask` that runs `libuv.run` in nowait mode, the problem with that is you will have to be calling it at a constant rate wasting CPU cycles or you won't be processing events as you receive them, a tradeoff.

With that being said, thanks for everyone's suggestions here, it was a great help!
