### ISSUE TITLE
Will libyue ever come to luarocks, the Lua package manager?

### ISSUE THREAD

**Issue by Frityet** [yue/yue#158]
[Luarocks](https://luarocks.org/) is the "de facto" standard package manager for lua, will libyue ever be added? I can create a PR to add it but i am not sure if its appreciated.

**Comment by zcbenz** [comment]
I do want to put yue in luarocks but I don't know how it works for C++ modules and I haven't got a chance to look into it, I will really appreciate it if you can help on this!

**Comment by M1NGS** [comment]
> 

 Makefile加一个luarocks的描述文件就行了

**Comment by Frityet** [comment]
> I do want to put yue in luarocks but I don't know how it works for C++ modules and I haven't got a chance to look into it, I will really appreciate it if you can help on this!

The best way is probably to have a makefile or a cmakelists.txt. Using [this](https://luarocks.org/modules/osch/luarocks-build-extended) package you can compile C++! I will try and make a package, and let you upload it with my PR

**Comment by wahern** [comment]
FWIW, attached is Makefile.yue, a build that wrote for my app. It comes with caveats, so it's perhaps more of a potential jumping-off point.

* It relies on the published assets archive to avoid dependencies on GN, etc. All it requires externally is Xcode and a regular macOS environment. Internal script dependencies are attached, but these should be rather trivial to remove--guess.mk macros aren't really needed if you assume GNU Make (I use it for portable Makefile introspection and conditionals; in this case I think only for the $(OS) macro, which is just `uname -s` lower-cased); fetch.sh is a wrapper around curl/wget/BSD ftp; sha256.sh is a wrapper around shasum/sha256/sha256sum.
* It only builds for and on macOS. I haven't had the time to port the GUI portions of my app to Windows or Gtk, yet.
* It's still at version 0.11.0, and in addition to LIBYUE_SHA256 and YUE_TAG typically requires manually updating the LIBYUE_SRCS macros for each version upgrade. For example, 0.10.3 - 0.11.0 required adding base/base_jumbo_8.cc to LIBYUE_SRCS. Also, looking at the diff I had to switch -std=c++14 to -std=c++17 to YUE_CXXFLAGS.
* It depends on GNU Make; Apple's 3.81 fork is fine. Most of it is structured as a portable (GNU/BSD/Sun compatible, but not strict POSIX) Makefile, which is why most conditionals employ recursive macro expansion rather than GNU Make imperative-style blocks.

Note: I had to add .txt extension to the files to attach to this post.
[Makefile.yue.txt](https://github.com/yue/yue/files/11181589/Makefile.yue.txt)
[guess.mk.txt](https://github.com/yue/yue/files/11181591/guess.mk.txt)
[fetch.sh.txt](https://github.com/yue/yue/files/11181594/fetch.sh.txt)
[sha256.sh.txt](https://github.com/yue/yue/files/11181595/sha256.sh.txt)

**Comment by Frityet** [comment]
> FWIW, attached is Makefile.yue, a build that wrote for my app. It comes with caveats, so it's perhaps more of a potential jumping-off point.
> 
>     * It relies on the published assets archive to avoid dependencies on GN, etc. All it requires externally is Xcode and a regular macOS environment. Internal script dependencies are attached, but these should be rather trivial to remove--guess.mk macros aren't really needed if you assume GNU Make (I use it for portable Makefile introspection and conditionals; in this case I think only for the $(OS) macro, which is just `uname -s` lower-cased); fetch.sh is a wrapper around curl/wget/BSD ftp; sha256.sh is a wrapper around shasum/sha256/sha256sum.
> 
>     * It only builds for and on macOS. I haven't had the time to port the GUI portions of my app to Windows or Gtk, yet.
> 
>     * It's still at version 0.11.0, and in addition to LIBYUE_SHA256 and YUE_TAG typically requires manually updating the LIBYUE_SRCS macros for each version upgrade. For example, 0.10.3 - 0.11.0 required adding base/base_jumbo_8.cc to LIBYUE_SRCS. Also, looking at the diff I had to switch -std=c++14 to -std=c++17 to YUE_CXXFLAGS.
> 
>     * It depends on GNU Make; Apple's 3.81 fork is fine. Most of it is structured as a portable (GNU/BSD/Sun compatible, but not strict POSIX) Makefile, which is why most conditionals employ recursive macro expansion rather than GNU Make imperative-style blocks.
> 
> 
> Note: I had to add .txt extension to the files to attach to this post. [Makefile.yue.txt](https://github.com/yue/yue/files/11181589/Makefile.yue.txt) [guess.mk.txt](https://github.com/yue/yue/files/11181591/guess.mk.txt) [fetch.sh.txt](https://github.com/yue/yue/files/11181594/fetch.sh.txt) [sha256.sh.txt](https://github.com/yue/yue/files/11181595/sha256.sh.txt)

Thank you! Ill use this as a reference

**Comment by Frityet** [comment]
https://luarocks.org/modules/Frityet/luayue-bin

Added (as binaries) to luarocks!

**Comment by Frityet** [comment]
Now I am going to work on a "compiled" version

**Comment by Frityet** [comment]
Got compilation working (just for MacOS-x64 right now)! [Check it out](https://github.com/Frityet/luayue/tree/compile)

**Comment by Frityet** [comment]
100% working

https://luarocks.org/modules/Frityet/luayue
