### ISSUE TITLE
live json stylesheet parser

### ISSUE THREAD

**Issue by hyphenlee** [yue/yue#174]
I want to do some work about making a runtime live style sheet loder.
will import a json library to parse json style sheet file like this:
```json
{
  "Button":{
  "color": "red",
  "flex-direction": "row"
  }
}
```
connect this json file with root window, and reload it when changed.
when apply it, I will search all child window and child view with the same class name.  
Maybe we should have a object name here to have a more accurate style control?
and select the object like this:
```json
{
  "#button_confirm":{
    "color": "green",
}
}
```
and maybe more complex object selector:
```json
{
  "Button#button_a,#button_b,":{
    "color": "green",
  }
}
```
Currently I plan to use https://github.com/nlohmann/json , but this library  not support json5, with json5 we can omit the double quote in key.
@zcbenz

**Comment by zcbenz** [comment]
Thanks for filing this!

Currently I don't plan to add high level features like this. The main reason is that this library is designed to be used in script environments like Node.js, where high level features like this are easy to implement with various modules instead of hardcore C++. 

Another reason is that it is hard to predict what is the best way to style the app: [GTK uses CSS](https://docs.gtk.org/gtk3/css-overview.html), [React Native uses StyleSheet object](https://reactnative.dev/docs/stylesheet), and [SwiftUI uses declarative syntax](https://developer.apple.com/xcode/swiftui/). So I would like to only keep basic layout ability at current stage.

But if you decide to write a library that implements this feature, I would be very happy to add link to your project in the homepage.

**Comment by hyphenlee** [comment]
It depends on what you want, a stylesheet or a view element declaration like QML?
I think a stylesheet loader is more practical, while a QML or swift UI like system is more complicated for a none profit project. 
I have seen xml support in your road map file, is it for UI element or stylesheet?
and if I write a library to depend on this library, is it possible to add something like object name in this library?

**Comment by zcbenz** [comment]
Currently I don't have a strong preference for the styling mechanism, and I don't want to add one for now.

The roadmap file is actually quite outdated and I even forgot it exists, I think I should just remove it.

I'm good adding support for object names in this library.

**Comment by hyphenlee** [comment]
> Currently I don't have a strong preference for the styling mechanism, and I don't want to add one for now.
> 
> The roadmap file is actually quite outdated and I even forgot it exists, I think I should just remove it.
> 
> I'm good adding support for object names in this library.

ok，I will try to make a new library for this feature, I will be glad  if it could be merged in sometimes later.

**Comment by justdie386** [comment]
@hyphenlee any progress? I recently had this exact idea and I was wondering if I should try implementing it as well (I’m using the Lua bindings so it’ll be written probably in Lua)

**Comment by hyphenlee** [comment]
@justdie386 I have write a demo under windows with win32 API in C++ to monitor json  style sheet file change, and set style in runtime when you save the style sheet file. if you want I can upload it to my repository. It can only control the the style by class name. To control the instance of a class require to add a object name in the View/Window class.
