### ISSUE TITLE
Errors that thrown from gui callbacks don't show in node std.

### ISSUE THREAD

**Issue by oyyd** [yue/yue#40]
The button below is expected to throw an error and log the error in my node process when clicked:

```js
const gui = require('gui')

const win = gui.Window.create({})
win.setContentSize({ width: 400, height: 400 })
win.onClose = () => gui.lifetime.quit()

const contentView = gui.Container.create()
contentView.setStyle({ flexDirection: 'row' })
win.setContentView(contentView)

const btnA = gui.Button.create('a')
contentView.addChildView(btnA)

// throw when this button is clicked
btnA.onClick = () => {
  throw new Error('invalid')
}

win.center()
win.activate()

if (!process.versions.yode) {
  gui.MessageLoop.run()
  process.exit(0)
}
```

But it doesn't. 

I could `catch` the error in the callback. But this would make debugging much more difficult when developing.

**Comment by zcbenz** [comment]
On this problem, the only way to solve it is to use https://github.com/yue/yode to run the app. For the official Node.js runtime, once the app entered GUI message loop with `gui.MessageLoop.run`, it would ignore exceptions happened in recursive `MakeCallback`s.

I'm closing this since I can not find a workaround in official Node.js runtime.
