### ISSUE TITLE
Forcing a repaint on a Container

### ISSUE THREAD

**Issue by caguiclajmg** [yue/yue#73]
**Platform**: Node.JS (11.5.0) on macOS (10.12)
**Yue**: 0.6.2
**Description**: Forcing a repaint via `schedulePaint()` doesn't yield expected behavior

```js
const container = gui.Container.create();

container.onDraw = (self, painter) => {
    // draw stuff
    self.schedulePaint();
}
```

Shouldn't the above trigger another repaint immediately? What currently happens is `onDraw` is called a few times (3 times, to be exact) upon startup and never again (aside from blur, focus and resize events).

**Comment by zcbenz** [comment]
`schedulePaint` works by marking the view as dirty instead of scheduling a `onDraw` (the API's name is probably misleading), when calling it inside a `onDraw` it won't have any effect as the view is already marked as dirty when `onDraw` is called.

If you are implementing things like a clock, just call `schedulePaint` in a timer.
